[phases.setup]
nixPkgs = ["nodejs_20", "bash"]

[phases.install]
cmd = "npm ci"

[phases.build]
cmd = "npm run build && mkdir -p .next/standalone/.next && cp -r .next/static .next/standalone/.next/static && cp -r public .next/standalone/public"

[start]
cmd = "npm start"
