[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "ffmpeg", "libGL", "libGLU", "glib"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt"]

[start]
cmd = "python3 main.py"
