[phases.setup]
nixPkgs = ["python3", "ffmpeg", "glib", "mesa", "libglvnd", "xorg.libX11", "xorg.libXext", "xorg.libXrender", "xorg.libICE", "xorg.libSM", "libGLU"]

[phases.install]
cmds = [
    "python3 -m venv /opt/venv",
    "/opt/venv/bin/pip install -r requirements.txt",
    "/opt/venv/bin/pip uninstall -y opencv-python || true",
    "/opt/venv/bin/pip install opencv-python-headless"
]

[start]
cmd = "/opt/venv/bin/python main.py"
